[[IgnoredVulns]]
id = "GHSA-pfrx-2q88-qq97"
reason = "...the built application is meant to be run on the client and not on the server... Look to https://github.com/qgis/QGIS/pull/55748#discussion_r1440141394"

[[IgnoredVulns]]
id = "GHSA-rc47-6667-2j5j"
reason = "...the built application is meant to be run on the client and not on the server... Look to https://github.com/qgis/QGIS/pull/55748#discussion_r1440141394"
