name: "🌈 Triage"

on:
  pull_request_target:
    types: [ opened, synchronize, reopened ]

permissions:
  contents: read

jobs:
  triage:
    name: "Set on PR"
    permissions:
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/labeler@8558fd74291d67161a8a78ce36a881fa63b766a9 # v5.0.0
        with:
          repo-token: "${{ secrets.GITHUB_TOKEN }}"
