name: Remove Labels

on: [issue_comment, pull_request]

permissions:
  contents: read

jobs:
  remove_labels:
    permissions:
      issues: write  # for actions-ecosystem/action-remove-labels to remove issue labels
      pull-requests: write  # for actions-ecosystem/action-remove-labels to remove PR labels
    if: contains(github.event.issue.labels.*.name, 'stale')
    runs-on: ubuntu-latest
    steps:
      - uses: actions-ecosystem/action-remove-labels@2ce5d41b4b6aa8503e285553f75ed56e0a40bae0 # v1.3.0
        if: ${{ github.event.comment.user.url != 'https://github.com/apps/github-actions' }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          labels: |
            stale
